### ISSUE TITLE
Getting the error `Instance method 'store(in:)' requires the types 'OpenCombine.AnyCancellable' and 'Combine.AnyCancellable' be equivalent`

### ISSUE THREAD

**Issue by doronkatz** [broadwaylamb/OpenCombine#120]
Hi folks.

Just started using this library, and got the following error:
```
Instance method 'store(in:)' requires the types 'OpenCombine.AnyCancellable' and 'Combine.AnyCancellable' be equivalent
```
This is within the block:
```
.receive(on: RunLoop.main)
                .sink(receiveCompletion: { (completion) in
                    if case let .failure(error) = completion {
                        switch error {
                        case let urlError as URLError:
                            promise(.failure(.urlError(urlError)))
                        case let decodingError as DecodingError:
                            promise(.failure(.decodingError(decodingError)))
                        case let apiError as APIError:
                            promise(.failure(apiError))
                        default:
                            promise(.failure(.genericError))
                        }
                    }
                }, receiveValue: { promise(.success($0.results)) })
                .store(in: &subscriptions)
            }
```
Let me know if you need any additional information, code context etc.

Thanks!

**Comment by broadwaylamb** [comment]
Hi!

The issue is that `RunLoop`'s conformance to the `Scheduler` protocol is not implemented yet (the `receive(on:)` method expects that its argument conforms to `Scheduler`).

You can import `OpenCombineDispatch` and use `.receive(on: DispatchQueue.main.ocombine)`. Note that due to how Swift works, invoking the `ocombine` property is _required_. Otherwise the compiler cannot determine which conformance to use: to the `Scheduler` protocol declared in Combine, or the same protocol declared in OpenCombine.

Let me know if this fixes your issue.

**Comment by doronkatz** [comment]
Thanks. Works like a charm. Good to know as well.
