### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by mc7h** [broadwaylamb/OpenCombine#134]
For and my team lack of support for Carthage dependency manager is a real barrier to adoption.

It would be great if OpenCombine [supported it ](https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework).

**Comment by broadwaylamb** [comment]
Out of curiosity, why is Swift Package Manager not something you can consider?

**Comment by mc7h** [comment]
We are considering it. However, the size and arrangement of the project is such that it's not feasible in the short or medium term. We depend on a number of internal, external (transitive and direct) libraries that do not support SPM. Our toolchain, build system and caching is heavily intertwined with Carthage also.

**Comment by c0diq** [comment]
Also it is not possible at the moment to link a SPM package as dynamic framework. Carthage does allow it and would permit to dynamically load OpenCombine at runtime when running below iOS 13.

**Comment by armintelker** [comment]
I would love to see this feature :)

**Comment by broadwaylamb** [comment]
As Carthage requires an Xcode project to be present in the repo, I don't think we'll support it in OpenCombine. Sorry.

Having an Xcode project in the repo that mainly targets Swift Package Manager is a maintenance burden, since you need to remember to synchronize the file structure between the repo and the Xcode project.

Besides, the feature for generating an Xcode project from the SPM manifest [has been deprecated](https://forums.swift.org/t/rfc-deprecating-generate-xcodeproj/42159).
