### ISSUE TITLE
Making testing helpers public

### ISSUE THREAD

**Issue by atimca** [broadwaylamb/OpenCombine#182]
Hello 👋

Due to lack of the testing SDK such in `RxSwift` with there `RxTesting` and `RxBlocking` for `Combine` or `Open Combine`. Would be great if you can put your testing stuff for public usage. After my short research, I've realized that `TrackingSubscriber` and friends could be a great replacement of `RxBlocking`.

**Comment by MaxDesiatov** [comment]
I concur, making these public would be great, what do you think @broadwaylamb?

**Comment by broadwaylamb** [comment]
I haven't put much effort into those APIs, they're very specific to our test suite. Making them more general will require some polishing that I'm afraid I don't have time for. Also, I sometimes have to change them in an incompatible way. Making them public would be additional headache for me, since I'd have to think about what changes are potentially breaking.

If you want, you can just copy and paste those classes into your test suite. Or even extract them into a separate project and evolve it independently. I guess a lot of people would be thankful.

**Comment by atimca** [comment]
All right. I've migrated library Entwine to OpenCombine if someone wants to test their code not only with expectations. 

https://github.com/Atimca/OpenEntwine
