### ISSUE TITLE
Merging efforts

### ISSUE THREAD

**Issue by AlexisQapa** [broadwaylamb/OpenCombine#80]
Hi,

Thank you for tackling the combine requirements issue. I believe this will help a lot but will require a lot of contributions. 

There is another port being build at https://github.com/cx-org/CombineX.
Maybe you could merge yours efforts ? I'm opening the same issue on the other repo.

**Comment by broadwaylamb** [comment]
Hi!

The author of CombineX has reached out before (see #4) and said that they would contribute to OpenCombine instead of developing their own project, but for some reason changed their mind.

In no way am I judging them, working on a project like this is indeed too much fun to be left for somebody else :)

I've looked at CombineX before and I can tell that there's a significant difference at how we see the development process and the little things like coding style, git workflow, implementation details etc.

That's why I think that at this point merging efforts would actually slow down the development process.

**Comment by AlexisQapa** [comment]
Good to know, sorry I missed the issue.

**Comment by ddddxxx** [comment]
Corresponding issue: cx-org/CombineX#19
